name: Daily Space Fact Sender

on:
  schedule:
    - cron: '0 3 * * *' # Daily at 8:30 AM IST (3 AM UTC)
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Output Folder
        run: mkdir -p out

      - name: Compile Java with External Libraries
        run: javac -cp "libs/*" src/*.java -d out

      - name: Run Main class
        run: java -cp "libs/*:out" Main
        env:
          nasa_api_key: ${{ secrets.NASA_API_KEY }}
          email_sender: ${{ secrets.EMAIL_SENDER }}
          email_password: ${{ secrets.EMAIL_PASSWORD }}
          email_recipient: ${{ secrets.EMAIL_RECIPIENT }}
